version: "3"

services:
  webserver:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    environment:
      - VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/:ro
